name: Deploy Frontend Only

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  REPOSITORY: lens
  SERVICE: lens-frontend
  REGION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Configure Docker for GAR
      run: |
        gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
    
    - name: Build and Push Frontend
      run: |
        IMAGE="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/frontend:${{ github.sha }}"
        docker build -f ./frontend/Dockerfile.simple -t $IMAGE ./frontend
        docker push $IMAGE
        echo "Frontend image: $IMAGE" >> $GITHUB_STEP_SUMMARY
    
    - name: Get Backend URL
      id: backend-url
      run: |
        BACKEND_URL=$(gcloud run services describe lens-api --region ${{ env.REGION }} --format 'value(status.url)')
        echo "Backend URL: $BACKEND_URL"
        echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT
    
    - name: Deploy Frontend to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE }}
        image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/frontend:${{ github.sha }}
        region: ${{ env.REGION }}
        env_vars: |
          NEXT_PUBLIC_API_URL=${{ steps.backend-url.outputs.url }}
        flags: |
          --port=3000
          --cpu=1
          --memory=1Gi
          --min-instances=0
          --max-instances=5
          --allow-unauthenticated
    
    - name: Show Output
      run: |
        echo "🎉 Frontend deployed successfully!" >> $GITHUB_STEP_SUMMARY
        echo "Frontend URL: ${{ steps.deploy.outputs.url }}" >> $GITHUB_STEP_SUMMARY
        echo "Connected to Backend: ${{ steps.backend-url.outputs.url }}" >> $GITHUB_STEP_SUMMARY